#!/bin/bash

for i in "$@"
do
case $i in
# Read the option for Chemistry kinetic mechanism.
# Accepted values: racm, racm2, cb05, melchior2
# Default: chemistry=cb05
    -c=*|--chemistry=*)
    chemistry="${i#*=}"
    shift
    ;;
# for genoa
# Default: genoa = no    
    -g=*|--genoa=*)
    genoa="${i#*=}"
    shift
    ;;
esac
done

# for genoa
if [ -z $genoa ]; then                     
    genoa="no"

elif [[ $genoa == "fast" || $genoa == "complete" ]]; then             

    # active tag
    echo "GENOA version : $genoa"
    # default to use genoa folder
    chemistry="genoa"
fi

if [ -z $chemistry ]; then
    chemistry="cb05"
fi
echo "Chemistry: $chemistry"

cd src
scons -c chemistry=$chemistry genoa=$genoa

rm -f `find -iname "*.bck"` 
rm -f `find -iname "*.o"`
rm -f `find -iname "*.os"`
rm -f `find -iname "ssh-aerosol-*"`
rm -f libssh-aerosol.so
rm -rf .scon*

cd ..

file="unifac.csv"
if [ -f $file ] 
then
    rm -f $file
fi


file="ssh-aerosol-cb05"
if [ -h $file ] 
then
    rm -f $file
fi

file="ssh-aerosol-cb05en"
if [ -h $file ] 
then
    rm -f $file
fi

file="ssh-aerosol"
if [ -h $file ] 
then
    rm -f $file
fi

file="namelist.out"
if [ -f $file ] 
then
    rm -f $file
fi

if [[ $genoa != "fast" && $genoa != "complete" ]]; then
    # default
    cd species-list
    rm -f `find -iname "species-list.dat"` 
    cd ../
    # remove temporary files
    cd src/include/CHEMISTRY/$chemistry
    rm -f `find -iname "combined_*.dat"`
    cd ../../spack/src/
    # avoid deletion of files in genoa/
    rm -f `find -iname "generate_chem_files.sh" ! -path "*/genoa/spack/src/generate_chem_files.sh"`
    cd ../../
fi

# deep clean if fast mode
if [[ $genoa == "fast" ]]; then

    # Check if needs a deep clean
    if [[ -d "src/include/CHEMISTRY" ]]; then
        # List of files/folders to exclude
        excluded=("clean" "cleantmp" "src" "compile")

        # Loop through all items in the current directory
        for item in *; do
            # Check if the item should be excluded
            if ! [[ "${excluded[@]}" =~ "$item" ]]; then
                # Remove the item (file or directory)
                rm -r "$item"
                echo "Removed: $item"
            fi
        done
    
        rm -rf "src/include/CHEMISTRY"
        echo "Removed: src/include/CHEMISTRY"

        rm -rf "src/include/spack"
        echo "Removed: src/include/spack"
    fi
    
fi

# file="combined_reactions.dat"
# if [ -f $file ] 
# then
#     rm -f $file
# fi
# file="combined_species.dat"
# if [ -f $file ] 
# then
#     rm -f $file
# fi
# cd ..




# if [ "$1" = "all" ]; then
#    lst=`ls -d tmp* 2>/dev/null`
#    for di in ${lst}; do
#       [ -d ${di} ] && { echo "removing ${di}...";  rm -rf ${di}; }
#    done
#    rm -rf ./exe-*
# fi
# echo "Remaining .nc files:"
# find -iname "*.nc"
# echo -n "Total directory space: "
# du -sh .
