#!/bin/bash

for i in "$@"
do
case $i in
# Read the option for Chemistry kinetic mechanism.
# Accepted values: racm, racm2, cb05, melchior2
# Default: chemistry=cb05
    -c=*|--chemistry=*)
    chemistry="${i#*=}"
    shift
    ;;
esac
done
if [ -z $chemistry ]; then
    chemistry="cb05"
fi
echo "Chemistry: $chemistry"

cd src
scons -c chemistry=$chemistry

rm -f `find -iname "*.bck"` 
rm -f `find -iname "*.o"`
rm -f `find -iname "*.os"`
rm -f `find -iname "ssh-aerosol-*"`
rm -f libssh-aerosol.so
rm -rf .scon*

cd ..

file="unifac.csv"
if [ -f $file ] 
then
    rm -f $file
fi


file="ssh-aerosol-cb05"
if [ -h $file ] 
then
    rm -f $file
fi

file="ssh-aerosol-cb05en"
if [ -h $file ] 
then
    rm -f $file
fi

file="ssh-aerosol"
if [ -h $file ] 
then
    rm -f $file
fi

file="namelist.out"
if [ -f $file ] 
then
    rm -f $file
fi

cd species-list
rm -f `find -iname "species-list.dat"` 
cd ../

# remove temporary files
cd src/include/CHEMISTRY/$chemistry
rm -f `find -iname "combined_*.dat"`
cd ../../spack/src/
rm -f `find -iname "generate_chem_files.sh"`
cd ../../


# file="combined_reactions.dat"
# if [ -f $file ] 
# then
#     rm -f $file
# fi
# file="combined_species.dat"
# if [ -f $file ] 
# then
#     rm -f $file
# fi
# cd ..




# if [ "$1" = "all" ]; then
#    lst=`ls -d tmp* 2>/dev/null`
#    for di in ${lst}; do
#       [ -d ${di} ] && { echo "removing ${di}...";  rm -rf ${di}; }
#    done
#    rm -rf ./exe-*
# fi
# echo "Remaining .nc files:"
# find -iname "*.nc"
# echo -n "Total directory space: "
# du -sh .
