#!/bin/bash

chemistry=$1

if [ -z $chemistry ]; then
  chemistry="cb05"
fi

# clean for genoa
if [ $chemistry == "genoa" ]; then
  
  for i in dimensions.f90 dratedc.f90 fexchem.f90 jacdchemdc.f90 kinetic.f90 rates.f90 LU_decompose.f90 LU_solve.f90 LU_solve_tr.f90 fexloss.f90 fexprod.f90 species.spack.dat species-list.dat
  do
    rm -rf src/include/genoa/CHEMISTRY/genoa/${i}
  done

# clean for other chemistry
else

  echo "cleaning $chemistry repository"

  for i in dimensions.f90 dratedc.f90 fexchem.f90 jacdchemdc.f90 kinetic.f90 rates.f90 LU_decompose.f90 LU_solve.f90 LU_solve_tr.f90 fexloss.f90 fexprod.f90 species.spack.dat species-list.dat
  do
    rm -rf src/include/CHEMISTRY/$1/${i}
  done
  
fi
