#!/bin/bash

for i in dimensions.f90 dratedc.f90 fexchem.f90 fexprod.f90 fexloss.f90 jacdchemdc.f90 kinetic.f90 rates.f90 LU_decompose.f90 LU_solve.f90 LU_solve_tr.f90
do
  rm -rf src/include/CHEMISTRY/*/${i}
done
