#!/bin/bash

# Read the option for Chemistry kinetic mechanism.
# Accepted values: racm, racm2, cb05
# Default: chemistry=cb05
for i in "$@"
do
case $i in
    -c=*|--chemistry=*)
    chemistry="${i#*=}"
    shift
    ;;
esac
done
if [ -z $chemistry ]; then
    chemistry="cb05en"
fi
echo "Chemistry: $chemistry"

# Read the option to choose whether Na and Cl are taken into account.
# Accepted values: yes or no
# Default: nacl = no
for i in "$@"
do
case $i in
    -n=*|--nacl=*)
    nacl="${i#*=}"
    shift
    ;;
esac
done
if [ -z $nacl ]; then
    nacl="no"
fi
echo "NaCl: $nacl"

# Read the option to choose whether openmp is taken into account.
# Accepted values: yes or no
# Default: openmp = no
for i in "$@"
do
case $i in
    -o=*|--openmp=*)
    openmp="${i#*=}"
    shift
    ;;
esac
done
if [ -z $openmp ]; then
    openmp="no"
fi
echo "OpenMP: $openmp"

# Read the option to generate a shared lib
# Accepted values: yes or no
# Default: sharedlib = no
for i in "$@"                                                       
do
case $i in
    -s=*|--sharedlib=*)      
    sharedlib="${i#*=}"        
    shift                       
    ;;                              
esac                                
done 
if [ -z $sharedlib ]; then                     
    sharedlib="no"                
fi
echo "SharedLib: $sharedlib"

file="ssh-aerosol"
if [ -h $file ] 
then
    rm -f $file
fi

./cleantmp

cd src
#scons -j8 profile=debug mode_fortran=strict line=yes chemistry=$chemistry nacl=$nacl openmp=no sharedlib=no
scons -j8 chemistry=$chemistry nacl=$nacl openmp=$openmp sharedlib=$sharedlib

cd ..
ln -s src/ssh-aerosol-$chemistry ssh-aerosol
