#!/bin/bash

for i in "$@"
do
case $i in
# Read the option for Chemistry kinetic mechanism.
# Accepted values: racm, racm2, cb05, melchior2
# Default: chemistry=cb05
    -c=*|--chemistry=*)
    chemistry="${i#*=}"
    shift
    ;;
# Read the option to generate a shared lib
# Accepted values: yes or no
# Default: sharedlib = no
    -s=*|--sharedlib=*)      
    sharedlib="${i#*=}"        
    shift                       
    ;;                              
# Read the option to choose whether Na and Cl are taken into account.
# Accepted values: yes or no
# Default: nacl = no
    -n=*|--nacl=*)
    nacl="${i#*=}"
    shift
    ;;
# Read the option to choose whether openmp is taken into account.
# Accepted values: yes or no
# Default: openmp = no
    -o=*|--openmp=*)
    openmp="${i#*=}"
    shift
    ;;
esac
done


if [ -z $chemistry ]; then
    chemistry="melchior2"
fi
echo "Chemistry: $chemistry"

if [ -z $nacl ]; then
    nacl="no"
fi
echo "NaCl: $nacl"

if [ -z $openmp ]; then
    openmp="no"
fi
echo "OpenMP: $openmp"

if [ -z $sharedlib ]; then                     
    sharedlib="no"                
fi
echo "SharedLib: $sharedlib"

file="ssh-aerosol"
if [ -h $file ] 
then
    rm -f $file
fi

./cleantmp $chemistry

cd src
#scons -j8 profile=debug mode_fortran=strict line=yes chemistry=$chemistry nacl=$nacl openmp=no sharedlib=no
scons -j8 chemistry=$chemistry nacl=$nacl openmp=$openmp sharedlib=$sharedlib 

cd ..
ln -s src/ssh-aerosol-$chemistry ssh-aerosol
