import distutils.sysconfig


if ARGUMENTS["swig"] == None:
   SWIGBIN = "swig"
else:
   SWIGBIN = ARGUMENTS["swig"]		

env = Environment(SWIGFLAGS = ['-c++', '-python'],
                  CPPPATH = [distutils.sysconfig.get_python_inc()],
                  SHLIBPREFIX = "",
		  SWIG = SWIGBIN)

if ARGUMENTS["intel"] == "yes":
    cpp_compiler = "icpc"

env.SharedLibrary('_talos.so', ['Talos.cpp', 'talos.i'])
