
      subroutine ssh_write_common_header_90(nwrite)
      integer nwrite

      write(nwrite,200)
      write(nwrite,101)
 101  format('!',5x,'This file was automatically generated by SPACK.')
      write(nwrite,200)
      write(nwrite,300)


 150  format('!',6x,a65)
 200  format('!-----------------------------------',
     2     '-------------------------------------')
 300  format('')

      RETURN
      END
