!------------------------------------------------------------------------
!     This file was automatically generated by SPACK.
!------------------------------------------------------------------------

subroutine ssh_dimensions                        ( &
    Ns, Nr, Nr_photolysis)

!------------------------------------------------------------------------
!
  integer Ns, Nr, Nr_photolysis

  Ns =    88
  Nr =   168
  Nr_photolysis =    22

return
end

