!!------------------------------------------------------------------------
!!      This file was automatically generated by SPACK.
!!------------------------------------------------------------------------

SUBROUTINE SSH_LU_solve_tr (ns, M, x)

!------------------------------------------------------------------------
!     
!     -- DESCRIPTION 
!     
!     This routine solves M^t * y = x where M is an LU factorization
!     computed by LU_decompose.
!	  This routine is automatically generated by LU.cpp
!     
!------------------------------------------------------------------------
!     
!     -- INPUT VARIABLES
!     
!	  nesp: matrix row number from the chemical species number
!     M: LU factorization computed by LU_decompose.
!     
!     -- INPUT/OUTPUT VARIABLES
!     
!     x: on entry, the right-hand side of the equation. On exit,
!     the solution of the equation.
!     
!     -- OUTPUT VARIABLES
!     
!------------------------------------------------------------------------
!     
!     -- REMARKS
!     
!------------------------------------------------------------------------
!     
!     -- MODIFICATIONS
!     
!------------------------------------------------------------------------
!     
!     -- AUTHOR(S)
!     
!------------------------------------------------------------------------

IMPLICIT NONE

INTEGER ns
DOUBLE PRECISION M(ns,ns)
DOUBLE PRECISION x(ns)
DOUBLE PRECISION temp


!     Forward substitution.

temp = M(3, 15) * x(3)
x(15) = x(15) - temp

temp = M(38, 45) * x(38)
x(45) = x(45) - temp

temp = M(24, 48) * x(24)
temp = temp + M(28, 48) * x(28)
x(48) = x(48) - temp

temp = M(38, 57) * x(38)
temp = temp + M(46, 57) * x(46)
temp = temp + M(47, 57) * x(47)
x(57) = x(57) - temp

temp = M(43, 59) * x(43)
temp = temp + M(44, 59) * x(44)
x(59) = x(59) - temp

temp = M(25, 60) * x(25)
x(60) = x(60) - temp

temp = M(50, 61) * x(50)
temp = temp + M(51, 61) * x(51)
x(61) = x(61) - temp

temp = M(54, 62) * x(54)
x(62) = x(62) - temp

temp = M(26, 63) * x(26)
x(63) = x(63) - temp

temp = M(66, 71) * x(66)
temp = temp + M(67, 71) * x(67)
temp = temp + M(70, 71) * x(70)
x(71) = x(71) - temp

temp = M(66, 72) * x(66)
temp = temp + M(67, 72) * x(67)
temp = temp + M(70, 72) * x(70)
x(72) = x(72) - temp

temp = M(36, 73) * x(36)
temp = temp + M(37, 73) * x(37)
temp = temp + M(38, 73) * x(38)
temp = temp + M(39, 73) * x(39)
temp = temp + M(40, 73) * x(40)
temp = temp + M(41, 73) * x(41)
temp = temp + M(42, 73) * x(42)
temp = temp + M(43, 73) * x(43)
temp = temp + M(44, 73) * x(44)
temp = temp + M(45, 73) * x(45)
temp = temp + M(46, 73) * x(46)
temp = temp + M(47, 73) * x(47)
temp = temp + M(53, 73) * x(53)
temp = temp + M(54, 73) * x(54)
temp = temp + M(57, 73) * x(57)
temp = temp + M(58, 73) * x(58)
temp = temp + M(59, 73) * x(59)
temp = temp + M(60, 73) * x(60)
temp = temp + M(62, 73) * x(62)
temp = temp + M(63, 73) * x(63)
temp = temp + M(64, 73) * x(64)
temp = temp + M(65, 73) * x(65)
temp = temp + M(68, 73) * x(68)
temp = temp + M(69, 73) * x(69)
x(73) = x(73) - temp

temp = M(4, 74) * x(4)
temp = temp + M(5, 74) * x(5)
temp = temp + M(6, 74) * x(6)
temp = temp + M(7, 74) * x(7)
temp = temp + M(8, 74) * x(8)
temp = temp + M(9, 74) * x(9)
temp = temp + M(10, 74) * x(10)
temp = temp + M(11, 74) * x(11)
temp = temp + M(12, 74) * x(12)
temp = temp + M(13, 74) * x(13)
temp = temp + M(14, 74) * x(14)
temp = temp + M(15, 74) * x(15)
temp = temp + M(16, 74) * x(16)
temp = temp + M(17, 74) * x(17)
temp = temp + M(18, 74) * x(18)
temp = temp + M(19, 74) * x(19)
temp = temp + M(21, 74) * x(21)
temp = temp + M(22, 74) * x(22)
temp = temp + M(23, 74) * x(23)
temp = temp + M(24, 74) * x(24)
temp = temp + M(26, 74) * x(26)
temp = temp + M(28, 74) * x(28)
temp = temp + M(29, 74) * x(29)
temp = temp + M(30, 74) * x(30)
temp = temp + M(31, 74) * x(31)
temp = temp + M(32, 74) * x(32)
temp = temp + M(33, 74) * x(33)
temp = temp + M(34, 74) * x(34)
temp = temp + M(35, 74) * x(35)
temp = temp + M(36, 74) * x(36)
temp = temp + M(37, 74) * x(37)
temp = temp + M(38, 74) * x(38)
temp = temp + M(39, 74) * x(39)
temp = temp + M(40, 74) * x(40)
temp = temp + M(41, 74) * x(41)
temp = temp + M(42, 74) * x(42)
temp = temp + M(43, 74) * x(43)
temp = temp + M(44, 74) * x(44)
temp = temp + M(45, 74) * x(45)
temp = temp + M(46, 74) * x(46)
temp = temp + M(47, 74) * x(47)
temp = temp + M(48, 74) * x(48)
temp = temp + M(49, 74) * x(49)
temp = temp + M(50, 74) * x(50)
temp = temp + M(51, 74) * x(51)
temp = temp + M(53, 74) * x(53)
temp = temp + M(54, 74) * x(54)
temp = temp + M(55, 74) * x(55)
temp = temp + M(56, 74) * x(56)
temp = temp + M(57, 74) * x(57)
temp = temp + M(58, 74) * x(58)
temp = temp + M(59, 74) * x(59)
temp = temp + M(60, 74) * x(60)
temp = temp + M(61, 74) * x(61)
temp = temp + M(62, 74) * x(62)
temp = temp + M(63, 74) * x(63)
temp = temp + M(64, 74) * x(64)
temp = temp + M(65, 74) * x(65)
temp = temp + M(68, 74) * x(68)
temp = temp + M(69, 74) * x(69)
temp = temp + M(71, 74) * x(71)
temp = temp + M(72, 74) * x(72)
temp = temp + M(73, 74) * x(73)
x(74) = x(74) - temp

temp = M(49, 76) * x(49)
temp = temp + M(61, 76) * x(61)
temp = temp + M(75, 76) * x(75)
x(76) = x(76) - temp

temp = M(29, 77) * x(29)
temp = temp + M(62, 77) * x(62)
temp = temp + M(63, 77) * x(63)
temp = temp + M(64, 77) * x(64)
temp = temp + M(65, 77) * x(65)
temp = temp + M(68, 77) * x(68)
temp = temp + M(69, 77) * x(69)
temp = temp + M(74, 77) * x(74)
temp = temp + M(75, 77) * x(75)
temp = temp + M(76, 77) * x(76)
x(77) = x(77) - temp

temp = M(27, 78) * x(27)
temp = temp + M(30, 78) * x(30)
temp = temp + M(74, 78) * x(74)
temp = temp + M(75, 78) * x(75)
temp = temp + M(76, 78) * x(76)
temp = temp + M(77, 78) * x(77)
x(78) = x(78) - temp

temp = M(43, 80) * x(43)
temp = temp + M(68, 80) * x(68)
temp = temp + M(69, 80) * x(69)
temp = temp + M(74, 80) * x(74)
temp = temp + M(75, 80) * x(75)
temp = temp + M(76, 80) * x(76)
temp = temp + M(77, 80) * x(77)
temp = temp + M(78, 80) * x(78)
temp = temp + M(79, 80) * x(79)
x(80) = x(80) - temp

temp = M(21, 81) * x(21)
temp = temp + M(22, 81) * x(22)
temp = temp + M(27, 81) * x(27)
temp = temp + M(52, 81) * x(52)
temp = temp + M(56, 81) * x(56)
temp = temp + M(70, 81) * x(70)
temp = temp + M(71, 81) * x(71)
temp = temp + M(72, 81) * x(72)
temp = temp + M(74, 81) * x(74)
temp = temp + M(75, 81) * x(75)
temp = temp + M(76, 81) * x(76)
temp = temp + M(77, 81) * x(77)
temp = temp + M(78, 81) * x(78)
temp = temp + M(79, 81) * x(79)
temp = temp + M(80, 81) * x(80)
x(81) = x(81) - temp

temp = M(48, 82) * x(48)
temp = temp + M(52, 82) * x(52)
temp = temp + M(60, 82) * x(60)
temp = temp + M(75, 82) * x(75)
temp = temp + M(76, 82) * x(76)
x(82) = x(82) - temp

temp = M(23, 83) * x(23)
temp = temp + M(29, 83) * x(29)
temp = temp + M(30, 83) * x(30)
temp = temp + M(32, 83) * x(32)
temp = temp + M(33, 83) * x(33)
temp = temp + M(35, 83) * x(35)
temp = temp + M(48, 83) * x(48)
temp = temp + M(49, 83) * x(49)
temp = temp + M(56, 83) * x(56)
temp = temp + M(65, 83) * x(65)
temp = temp + M(69, 83) * x(69)
temp = temp + M(70, 83) * x(70)
temp = temp + M(71, 83) * x(71)
temp = temp + M(72, 83) * x(72)
temp = temp + M(73, 83) * x(73)
temp = temp + M(74, 83) * x(74)
temp = temp + M(75, 83) * x(75)
temp = temp + M(76, 83) * x(76)
temp = temp + M(77, 83) * x(77)
temp = temp + M(78, 83) * x(78)
temp = temp + M(79, 83) * x(79)
temp = temp + M(80, 83) * x(80)
temp = temp + M(81, 83) * x(81)
temp = temp + M(82, 83) * x(82)
x(83) = x(83) - temp

temp = M(20, 84) * x(20)
temp = temp + M(25, 84) * x(25)
temp = temp + M(35, 84) * x(35)
temp = temp + M(36, 84) * x(36)
temp = temp + M(37, 84) * x(37)
temp = temp + M(38, 84) * x(38)
temp = temp + M(39, 84) * x(39)
temp = temp + M(40, 84) * x(40)
temp = temp + M(41, 84) * x(41)
temp = temp + M(42, 84) * x(42)
temp = temp + M(43, 84) * x(43)
temp = temp + M(44, 84) * x(44)
temp = temp + M(45, 84) * x(45)
temp = temp + M(46, 84) * x(46)
temp = temp + M(47, 84) * x(47)
temp = temp + M(50, 84) * x(50)
temp = temp + M(51, 84) * x(51)
temp = temp + M(53, 84) * x(53)
temp = temp + M(54, 84) * x(54)
temp = temp + M(57, 84) * x(57)
temp = temp + M(58, 84) * x(58)
temp = temp + M(59, 84) * x(59)
temp = temp + M(60, 84) * x(60)
temp = temp + M(61, 84) * x(61)
temp = temp + M(62, 84) * x(62)
temp = temp + M(63, 84) * x(63)
temp = temp + M(64, 84) * x(64)
temp = temp + M(65, 84) * x(65)
temp = temp + M(66, 84) * x(66)
temp = temp + M(67, 84) * x(67)
temp = temp + M(68, 84) * x(68)
temp = temp + M(69, 84) * x(69)
temp = temp + M(71, 84) * x(71)
temp = temp + M(72, 84) * x(72)
temp = temp + M(73, 84) * x(73)
temp = temp + M(74, 84) * x(74)
temp = temp + M(75, 84) * x(75)
temp = temp + M(76, 84) * x(76)
temp = temp + M(77, 84) * x(77)
temp = temp + M(78, 84) * x(78)
temp = temp + M(79, 84) * x(79)
temp = temp + M(80, 84) * x(80)
temp = temp + M(81, 84) * x(81)
temp = temp + M(82, 84) * x(82)
temp = temp + M(83, 84) * x(83)
x(84) = x(84) - temp

temp = M(32, 85) * x(32)
temp = temp + M(34, 85) * x(34)
temp = temp + M(74, 85) * x(74)
temp = temp + M(75, 85) * x(75)
temp = temp + M(76, 85) * x(76)
temp = temp + M(77, 85) * x(77)
temp = temp + M(78, 85) * x(78)
temp = temp + M(79, 85) * x(79)
temp = temp + M(80, 85) * x(80)
temp = temp + M(81, 85) * x(81)
temp = temp + M(82, 85) * x(82)
temp = temp + M(83, 85) * x(83)
temp = temp + M(84, 85) * x(84)
x(85) = x(85) - temp

temp = M(31, 86) * x(31)
temp = temp + M(33, 86) * x(33)
temp = temp + M(52, 86) * x(52)
temp = temp + M(70, 86) * x(70)
temp = temp + M(71, 86) * x(71)
temp = temp + M(72, 86) * x(72)
temp = temp + M(73, 86) * x(73)
temp = temp + M(74, 86) * x(74)
temp = temp + M(75, 86) * x(75)
temp = temp + M(76, 86) * x(76)
temp = temp + M(77, 86) * x(77)
temp = temp + M(78, 86) * x(78)
temp = temp + M(79, 86) * x(79)
temp = temp + M(80, 86) * x(80)
temp = temp + M(81, 86) * x(81)
temp = temp + M(82, 86) * x(82)
temp = temp + M(83, 86) * x(83)
temp = temp + M(84, 86) * x(84)
temp = temp + M(85, 86) * x(85)
x(86) = x(86) - temp

temp = M(20, 87) * x(20)
temp = temp + M(31, 87) * x(31)
temp = temp + M(34, 87) * x(34)
temp = temp + M(55, 87) * x(55)
temp = temp + M(61, 87) * x(61)
temp = temp + M(69, 87) * x(69)
temp = temp + M(73, 87) * x(73)
temp = temp + M(74, 87) * x(74)
temp = temp + M(75, 87) * x(75)
temp = temp + M(76, 87) * x(76)
temp = temp + M(77, 87) * x(77)
temp = temp + M(78, 87) * x(78)
temp = temp + M(79, 87) * x(79)
temp = temp + M(80, 87) * x(80)
temp = temp + M(81, 87) * x(81)
temp = temp + M(82, 87) * x(82)
temp = temp + M(83, 87) * x(83)
temp = temp + M(84, 87) * x(84)
temp = temp + M(85, 87) * x(85)
temp = temp + M(86, 87) * x(86)
x(87) = x(87) - temp

temp = M(55, 88) * x(55)
temp = temp + M(60, 88) * x(60)
temp = temp + M(62, 88) * x(62)
temp = temp + M(63, 88) * x(63)
temp = temp + M(64, 88) * x(64)
temp = temp + M(65, 88) * x(65)
temp = temp + M(66, 88) * x(66)
temp = temp + M(67, 88) * x(67)
temp = temp + M(68, 88) * x(68)
temp = temp + M(69, 88) * x(69)
temp = temp + M(71, 88) * x(71)
temp = temp + M(72, 88) * x(72)
temp = temp + M(73, 88) * x(73)
temp = temp + M(74, 88) * x(74)
temp = temp + M(75, 88) * x(75)
temp = temp + M(76, 88) * x(76)
temp = temp + M(77, 88) * x(77)
temp = temp + M(78, 88) * x(78)
temp = temp + M(79, 88) * x(79)
temp = temp + M(80, 88) * x(80)
temp = temp + M(81, 88) * x(81)
temp = temp + M(82, 88) * x(82)
temp = temp + M(83, 88) * x(83)
temp = temp + M(84, 88) * x(84)
temp = temp + M(85, 88) * x(85)
temp = temp + M(86, 88) * x(86)
temp = temp + M(87, 88) * x(87)
x(88) = x(88) - temp


!     Backward substitution.

x(88) = x(88) / M(88, 88)

temp = M(88, 87) * x(88)
x(87) = ( x(87) - temp ) / M(87, 87)

temp = M(87, 86) * x(87)
temp = temp + M(88, 86) * x(88)
x(86) = ( x(86) - temp ) / M(86, 86)

temp = M(86, 85) * x(86)
temp = temp + M(87, 85) * x(87)
temp = temp + M(88, 85) * x(88)
x(85) = ( x(85) - temp ) / M(85, 85)

temp = M(85, 84) * x(85)
temp = temp + M(86, 84) * x(86)
temp = temp + M(87, 84) * x(87)
temp = temp + M(88, 84) * x(88)
x(84) = ( x(84) - temp ) / M(84, 84)

temp = M(84, 83) * x(84)
temp = temp + M(85, 83) * x(85)
temp = temp + M(86, 83) * x(86)
temp = temp + M(87, 83) * x(87)
temp = temp + M(88, 83) * x(88)
x(83) = ( x(83) - temp ) / M(83, 83)

x(82) = x(82) / M(82, 82)

temp = M(82, 81) * x(82)
temp = temp + M(83, 81) * x(83)
temp = temp + M(84, 81) * x(84)
temp = temp + M(85, 81) * x(85)
temp = temp + M(86, 81) * x(86)
temp = temp + M(87, 81) * x(87)
temp = temp + M(88, 81) * x(88)
x(81) = ( x(81) - temp ) / M(81, 81)

temp = M(81, 80) * x(81)
temp = temp + M(82, 80) * x(82)
temp = temp + M(83, 80) * x(83)
temp = temp + M(84, 80) * x(84)
temp = temp + M(85, 80) * x(85)
temp = temp + M(86, 80) * x(86)
temp = temp + M(87, 80) * x(87)
temp = temp + M(88, 80) * x(88)
x(80) = ( x(80) - temp ) / M(80, 80)

x(79) = x(79) / M(79, 79)

temp = M(79, 78) * x(79)
temp = temp + M(80, 78) * x(80)
temp = temp + M(81, 78) * x(81)
temp = temp + M(82, 78) * x(82)
temp = temp + M(83, 78) * x(83)
temp = temp + M(84, 78) * x(84)
temp = temp + M(85, 78) * x(85)
temp = temp + M(86, 78) * x(86)
temp = temp + M(87, 78) * x(87)
temp = temp + M(88, 78) * x(88)
x(78) = ( x(78) - temp ) / M(78, 78)

temp = M(78, 77) * x(78)
temp = temp + M(79, 77) * x(79)
temp = temp + M(80, 77) * x(80)
temp = temp + M(81, 77) * x(81)
temp = temp + M(82, 77) * x(82)
temp = temp + M(83, 77) * x(83)
temp = temp + M(84, 77) * x(84)
temp = temp + M(85, 77) * x(85)
temp = temp + M(86, 77) * x(86)
temp = temp + M(87, 77) * x(87)
temp = temp + M(88, 77) * x(88)
x(77) = ( x(77) - temp ) / M(77, 77)

x(76) = x(76) / M(76, 76)

temp = M(76, 75) * x(76)
x(75) = ( x(75) - temp ) / M(75, 75)

temp = M(75, 74) * x(75)
temp = temp + M(76, 74) * x(76)
temp = temp + M(77, 74) * x(77)
temp = temp + M(78, 74) * x(78)
temp = temp + M(79, 74) * x(79)
temp = temp + M(80, 74) * x(80)
temp = temp + M(81, 74) * x(81)
temp = temp + M(82, 74) * x(82)
temp = temp + M(83, 74) * x(83)
temp = temp + M(84, 74) * x(84)
temp = temp + M(85, 74) * x(85)
temp = temp + M(86, 74) * x(86)
temp = temp + M(87, 74) * x(87)
temp = temp + M(88, 74) * x(88)
x(74) = ( x(74) - temp ) / M(74, 74)

temp = M(74, 73) * x(74)
temp = temp + M(75, 73) * x(75)
temp = temp + M(77, 73) * x(77)
temp = temp + M(78, 73) * x(78)
temp = temp + M(79, 73) * x(79)
temp = temp + M(80, 73) * x(80)
temp = temp + M(81, 73) * x(81)
temp = temp + M(82, 73) * x(82)
temp = temp + M(83, 73) * x(83)
temp = temp + M(84, 73) * x(84)
temp = temp + M(85, 73) * x(85)
temp = temp + M(86, 73) * x(86)
temp = temp + M(87, 73) * x(87)
temp = temp + M(88, 73) * x(88)
x(73) = ( x(73) - temp ) / M(73, 73)

x(72) = x(72) / M(72, 72)

x(71) = x(71) / M(71, 71)

x(70) = x(70) / M(70, 70)

temp = M(74, 69) * x(74)
temp = temp + M(84, 69) * x(84)
temp = temp + M(87, 69) * x(87)
x(69) = ( x(69) - temp ) / M(69, 69)

temp = M(74, 68) * x(74)
temp = temp + M(79, 68) * x(79)
temp = temp + M(83, 68) * x(83)
x(68) = ( x(68) - temp ) / M(68, 68)

x(67) = x(67) / M(67, 67)

x(66) = x(66) / M(66, 66)

temp = M(83, 65) * x(83)
temp = temp + M(84, 65) * x(84)
temp = temp + M(87, 65) * x(87)
temp = temp + M(88, 65) * x(88)
x(65) = ( x(65) - temp ) / M(65, 65)

temp = M(68, 64) * x(68)
temp = temp + M(69, 64) * x(69)
temp = temp + M(74, 64) * x(74)
temp = temp + M(81, 64) * x(81)
temp = temp + M(83, 64) * x(83)
temp = temp + M(84, 64) * x(84)
temp = temp + M(86, 64) * x(86)
x(64) = ( x(64) - temp ) / M(64, 64)

temp = M(64, 63) * x(64)
temp = temp + M(74, 63) * x(74)
temp = temp + M(78, 63) * x(78)
temp = temp + M(86, 63) * x(86)
x(63) = ( x(63) - temp ) / M(63, 63)

temp = M(63, 62) * x(63)
temp = temp + M(64, 62) * x(64)
temp = temp + M(65, 62) * x(65)
temp = temp + M(68, 62) * x(68)
temp = temp + M(74, 62) * x(74)
temp = temp + M(83, 62) * x(83)
temp = temp + M(86, 62) * x(86)
x(62) = ( x(62) - temp ) / M(62, 62)

temp = M(75, 61) * x(75)
x(61) = ( x(61) - temp ) / M(61, 61)

x(60) = x(60) / M(60, 60)

temp = M(64, 59) * x(64)
temp = temp + M(65, 59) * x(65)
temp = temp + M(68, 59) * x(68)
temp = temp + M(73, 59) * x(73)
temp = temp + M(74, 59) * x(74)
temp = temp + M(78, 59) * x(78)
temp = temp + M(80, 59) * x(80)
temp = temp + M(83, 59) * x(83)
temp = temp + M(84, 59) * x(84)
temp = temp + M(87, 59) * x(87)
x(59) = ( x(59) - temp ) / M(59, 59)

x(58) = x(58) / M(58, 58)

temp = M(58, 57) * x(58)
temp = temp + M(63, 57) * x(63)
temp = temp + M(64, 57) * x(64)
temp = temp + M(65, 57) * x(65)
temp = temp + M(68, 57) * x(68)
temp = temp + M(73, 57) * x(73)
temp = temp + M(74, 57) * x(74)
temp = temp + M(77, 57) * x(77)
temp = temp + M(78, 57) * x(78)
temp = temp + M(80, 57) * x(80)
temp = temp + M(83, 57) * x(83)
temp = temp + M(84, 57) * x(84)
x(57) = ( x(57) - temp ) / M(57, 57)

temp = M(74, 56) * x(74)
temp = temp + M(80, 56) * x(80)
temp = temp + M(81, 56) * x(81)
temp = temp + M(83, 56) * x(83)
x(56) = ( x(56) - temp ) / M(56, 56)

temp = M(74, 55) * x(74)
temp = temp + M(87, 55) * x(87)
temp = temp + M(88, 55) * x(88)
x(55) = ( x(55) - temp ) / M(55, 55)

temp = M(68, 54) * x(68)
temp = temp + M(74, 54) * x(74)
temp = temp + M(83, 54) * x(83)
temp = temp + M(86, 54) * x(86)
x(54) = ( x(54) - temp ) / M(54, 54)

temp = M(54, 53) * x(54)
temp = temp + M(62, 53) * x(62)
temp = temp + M(64, 53) * x(64)
temp = temp + M(68, 53) * x(68)
temp = temp + M(73, 53) * x(73)
temp = temp + M(74, 53) * x(74)
temp = temp + M(78, 53) * x(78)
temp = temp + M(80, 53) * x(80)
temp = temp + M(83, 53) * x(83)
temp = temp + M(86, 53) * x(86)
x(53) = ( x(53) - temp ) / M(53, 53)

x(52) = x(52) / M(52, 52)

x(51) = x(51) / M(51, 51)

x(50) = x(50) / M(50, 50)

temp = M(76, 49) * x(76)
x(49) = ( x(49) - temp ) / M(49, 49)

x(48) = x(48) / M(48, 48)

x(47) = x(47) / M(47, 47)

x(46) = x(46) / M(46, 46)

temp = M(46, 45) * x(46)
temp = temp + M(47, 45) * x(47)
temp = temp + M(58, 45) * x(58)
temp = temp + M(63, 45) * x(63)
temp = temp + M(64, 45) * x(64)
temp = temp + M(65, 45) * x(65)
temp = temp + M(68, 45) * x(68)
temp = temp + M(73, 45) * x(73)
temp = temp + M(74, 45) * x(74)
temp = temp + M(77, 45) * x(77)
temp = temp + M(78, 45) * x(78)
temp = temp + M(80, 45) * x(80)
temp = temp + M(83, 45) * x(83)
temp = temp + M(84, 45) * x(84)
x(45) = ( x(45) - temp ) / M(45, 45)

temp = M(64, 44) * x(64)
temp = temp + M(68, 44) * x(68)
temp = temp + M(74, 44) * x(74)
temp = temp + M(87, 44) * x(87)
x(44) = ( x(44) - temp ) / M(44, 44)

x(43) = x(43) / M(43, 43)

temp = M(74, 42) * x(74)
temp = temp + M(81, 42) * x(81)
x(42) = ( x(42) - temp ) / M(42, 42)

temp = M(42, 41) * x(42)
temp = temp + M(43, 41) * x(43)
temp = temp + M(44, 41) * x(44)
temp = temp + M(64, 41) * x(64)
temp = temp + M(65, 41) * x(65)
temp = temp + M(68, 41) * x(68)
temp = temp + M(73, 41) * x(73)
temp = temp + M(74, 41) * x(74)
temp = temp + M(78, 41) * x(78)
temp = temp + M(80, 41) * x(80)
temp = temp + M(81, 41) * x(81)
temp = temp + M(83, 41) * x(83)
temp = temp + M(84, 41) * x(84)
x(41) = ( x(41) - temp ) / M(41, 41)

temp = M(54, 40) * x(54)
temp = temp + M(63, 40) * x(63)
temp = temp + M(68, 40) * x(68)
temp = temp + M(73, 40) * x(73)
temp = temp + M(74, 40) * x(74)
temp = temp + M(79, 40) * x(79)
temp = temp + M(80, 40) * x(80)
temp = temp + M(83, 40) * x(83)
temp = temp + M(85, 40) * x(85)
x(40) = ( x(40) - temp ) / M(40, 40)

temp = M(40, 39) * x(40)
temp = temp + M(41, 39) * x(41)
temp = temp + M(53, 39) * x(53)
temp = temp + M(60, 39) * x(60)
temp = temp + M(62, 39) * x(62)
temp = temp + M(65, 39) * x(65)
temp = temp + M(68, 39) * x(68)
temp = temp + M(73, 39) * x(73)
temp = temp + M(74, 39) * x(74)
temp = temp + M(77, 39) * x(77)
temp = temp + M(80, 39) * x(80)
temp = temp + M(82, 39) * x(82)
temp = temp + M(83, 39) * x(83)
temp = temp + M(84, 39) * x(84)
x(39) = ( x(39) - temp ) / M(39, 39)

x(38) = x(38) / M(38, 38)

temp = M(38, 37) * x(38)
temp = temp + M(46, 37) * x(46)
temp = temp + M(47, 37) * x(47)
temp = temp + M(58, 37) * x(58)
temp = temp + M(63, 37) * x(63)
temp = temp + M(64, 37) * x(64)
temp = temp + M(65, 37) * x(65)
temp = temp + M(68, 37) * x(68)
temp = temp + M(73, 37) * x(73)
temp = temp + M(74, 37) * x(74)
temp = temp + M(77, 37) * x(77)
temp = temp + M(78, 37) * x(78)
temp = temp + M(80, 37) * x(80)
temp = temp + M(83, 37) * x(83)
temp = temp + M(84, 37) * x(84)
x(37) = ( x(37) - temp ) / M(37, 37)

temp = M(38, 36) * x(38)
temp = temp + M(46, 36) * x(46)
temp = temp + M(47, 36) * x(47)
temp = temp + M(58, 36) * x(58)
temp = temp + M(63, 36) * x(63)
temp = temp + M(64, 36) * x(64)
temp = temp + M(65, 36) * x(65)
temp = temp + M(68, 36) * x(68)
temp = temp + M(73, 36) * x(73)
temp = temp + M(74, 36) * x(74)
temp = temp + M(77, 36) * x(77)
temp = temp + M(78, 36) * x(78)
temp = temp + M(80, 36) * x(80)
temp = temp + M(83, 36) * x(83)
temp = temp + M(84, 36) * x(84)
x(36) = ( x(36) - temp ) / M(36, 36)

temp = M(69, 35) * x(69)
temp = temp + M(74, 35) * x(74)
temp = temp + M(83, 35) * x(83)
temp = temp + M(84, 35) * x(84)
x(35) = ( x(35) - temp ) / M(35, 35)

temp = M(74, 34) * x(74)
temp = temp + M(79, 34) * x(79)
temp = temp + M(84, 34) * x(84)
temp = temp + M(85, 34) * x(85)
temp = temp + M(87, 34) * x(87)
x(34) = ( x(34) - temp ) / M(34, 34)

temp = M(74, 33) * x(74)
temp = temp + M(79, 33) * x(79)
temp = temp + M(81, 33) * x(81)
temp = temp + M(86, 33) * x(86)
x(33) = ( x(33) - temp ) / M(33, 33)

temp = M(74, 32) * x(74)
temp = temp + M(83, 32) * x(83)
temp = temp + M(85, 32) * x(85)
x(32) = ( x(32) - temp ) / M(32, 32)

temp = M(74, 31) * x(74)
temp = temp + M(79, 31) * x(79)
temp = temp + M(80, 31) * x(80)
temp = temp + M(84, 31) * x(84)
temp = temp + M(86, 31) * x(86)
temp = temp + M(87, 31) * x(87)
x(31) = ( x(31) - temp ) / M(31, 31)

temp = M(74, 30) * x(74)
temp = temp + M(78, 30) * x(78)
temp = temp + M(83, 30) * x(83)
x(30) = ( x(30) - temp ) / M(30, 30)

temp = M(74, 29) * x(74)
temp = temp + M(83, 29) * x(83)
x(29) = ( x(29) - temp ) / M(29, 29)

x(28) = x(28) / M(28, 28)

x(27) = x(27) / M(27, 27)

temp = M(86, 26) * x(86)
x(26) = ( x(26) - temp ) / M(26, 26)

x(25) = x(25) / M(25, 25)

x(24) = x(24) / M(24, 24)

x(23) = x(23) / M(23, 23)

x(22) = x(22) / M(22, 22)

temp = M(22, 21) * x(22)
temp = temp + M(74, 21) * x(74)
temp = temp + M(80, 21) * x(80)
temp = temp + M(81, 21) * x(81)
temp = temp + M(83, 21) * x(83)
x(21) = ( x(21) - temp ) / M(21, 21)

temp = M(69, 20) * x(69)
temp = temp + M(84, 20) * x(84)
temp = temp + M(87, 20) * x(87)
x(20) = ( x(20) - temp ) / M(20, 20)

temp = M(64, 19) * x(64)
temp = temp + M(74, 19) * x(74)
temp = temp + M(78, 19) * x(78)
x(19) = ( x(19) - temp ) / M(19, 19)

temp = M(72, 18) * x(72)
x(18) = ( x(18) - temp ) / M(18, 18)

temp = M(63, 17) * x(63)
temp = temp + M(64, 17) * x(64)
temp = temp + M(74, 17) * x(74)
temp = temp + M(78, 17) * x(78)
temp = temp + M(86, 17) * x(86)
x(17) = ( x(17) - temp ) / M(17, 17)

temp = M(43, 16) * x(43)
temp = temp + M(68, 16) * x(68)
temp = temp + M(74, 16) * x(74)
temp = temp + M(83, 16) * x(83)
x(16) = ( x(16) - temp ) / M(16, 16)

temp = M(16, 15) * x(16)
temp = temp + M(53, 15) * x(53)
temp = temp + M(54, 15) * x(54)
temp = temp + M(74, 15) * x(74)
temp = temp + M(78, 15) * x(78)
temp = temp + M(80, 15) * x(80)
temp = temp + M(83, 15) * x(83)
temp = temp + M(85, 15) * x(85)
x(15) = ( x(15) - temp ) / M(15, 15)

temp = M(15, 14) * x(15)
temp = temp + M(54, 14) * x(54)
temp = temp + M(74, 14) * x(74)
temp = temp + M(78, 14) * x(78)
x(14) = ( x(14) - temp ) / M(14, 14)

x(13) = x(13) / M(13, 13)

x(12) = x(12) / M(12, 12)

x(11) = x(11) / M(11, 11)

temp = M(13, 10) * x(13)
x(10) = ( x(10) - temp ) / M(10, 10)

temp = M(12, 9) * x(12)
x(9) = ( x(9) - temp ) / M(9, 9)

temp = M(11, 8) * x(11)
x(8) = ( x(8) - temp ) / M(8, 8)

temp = M(71, 7) * x(71)
x(7) = ( x(7) - temp ) / M(7, 7)

x(6) = x(6) / M(6, 6)

x(5) = x(5) / M(5, 5)

temp = M(5, 4) * x(5)
temp = temp + M(6, 4) * x(6)
temp = temp + M(63, 4) * x(63)
temp = temp + M(64, 4) * x(64)
temp = temp + M(74, 4) * x(74)
temp = temp + M(77, 4) * x(77)
x(4) = ( x(4) - temp ) / M(4, 4)

x(3) = x(3) / M(3, 3)

x(2) = x(2) / M(2, 2)

x(1) = x(1) / M(1, 1)


END
