!------------------------------------------------------------------------
!     This file was automatically generated by SPACK.
!------------------------------------------------------------------------

subroutine ssh_dimensions                        ( &
    Ns, Nr, Nr_photolysis)

!------------------------------------------------------------------------
!
  integer Ns, Nr, Nr_photolysis

  Ns =   511
  Nr =  1242
  Nr_photolysis =   248

return
end

