#!/bin/bash

#---------------------------------------------------------------------------------
#	Architecture file for compiling and running CHIMERE	
#	Specify path to libraries, compilers and utilities 
#---------------------------------------------------------------------------------


#---------------------------------------------------------------------------------
# 	Compilers
#---------------------------------------------------------------------------------
export my_compilerF90=				# Path to Fortran 90 compiler
export my_compilerC=				# Path to C compiler
export my_compilerCpp=				# Path to C++ compiler


#---------------------------------------------------------------------------------
# 	MPI - parallel execution of chimere
#---------------------------------------------------------------------------------
export  my_mpiframe=  			# implementaion of MPI norm [ ompi / ccrt ] TO REMOVE
export  my_mpibin=    			# Path to MPI binary directory
export  my_mpirun=    			# Path to mpirun to execute parallel job in MPI
export  my_mpif90=    			# Wrapper to my_compilerF90 to link with MPI library
export  my_mpicc=     			# Wrapper to my_compilerC to link with MPI library
export  my_mpilib=    			# Path to MPI libraries directory
export  my_mpiinc=    			# Path to MPI include files directory


#---------------------------------------------------------------------------------
# 	HDF5  - parallel version	
#---------------------------------------------------------------------------------
export my_hdflib=		# Path to HDF5 parallel library directory
export my_hdfinc=		# Path to HDF5 parallel include files directory


#---------------------------------------------------------------------------------
# 	NETCDF-C  - link with HDF5 parallel 
#---------------------------------------------------------------------------------
export my_netcdfCbin= 		# Path to NETCDF-C (linked with HDF5 parallel) binaries directory 
export my_netcdfClib=		# Path to NETCDF-C (linked with HDF5 parallel) library directory
export my_netcdfCinc=		# Path to NETCDF-C (linked with HDF5 parallel) include directory


#---------------------------------------------------------------------------------
# 	NETCDF-Fortran  - link with HDF5 parallel and NETCDF-C
#---------------------------------------------------------------------------------
export my_netcdfF90bin=         # PATH to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) binaries  directory
export my_netcdfF90lib=		# Path to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) library  directory
export my_netcdfF90inc=		# Path to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) include files  directory


#---------------------------------------------------------------------------------
# 	GRIB  - link with jasper 
#---------------------------------------------------------------------------------
export my_griblib=     			# Path to GRIB library directory
export my_gribinc= 			# Path to GRIB include files directory
export my_jasperlib= 			# Path to JASPER library directory
export my_jasperinc=			# Path to JASPER include files directory


#---------------------------------------------------------------------------------
# 	BLITZ
#---------------------------------------------------------------------------------
export my_blitzinc=		 # Path to BLITZ include files 


#---------------------------------------------------------------------------------
# 	Utilities	
#---------------------------------------------------------------------------------
export my_make= 		# Path to make 
export my_awk=			# Path to awk
export my_python3=		# Path to python3
export my_ncdump=		# Path to ncdump


#---------------------------------------------------------------------------------
# 	Makefile header needed to compile CHIMERE and WRF 
#	     - with this architecture configuration - 	
#---------------------------------------------------------------------------------
export my_hdr=   			# Makefile header to compile CHIMERE in makefiles.hdr directory
export configure_wrf_file_name=  	# Makefile header to compile WRF in config_wrf directory
export configure_wps_file_name=  	# Makefile header to compile WPS in config_wps directory
export configure_xios_file_name=    # Makefile header (*.fcm) to compile XIOS in config_xios directory


#---------------------------------------------------------------------------------
#	Export of Shared Library to be available at run time 	
#---------------------------------------------------------------------------------
export LD_LIBRARY_PATH=${my_hdflib}:${my_netcdfF90lib}:${my_netcdfClib}:${my_griblib}:${my_mpilib}:${my_mpilib}/openmpi:$LD_LIBRARY_PATH


#---------------------------------------------------------------------------------
# 	SSH-aerosol	
#---------------------------------------------------------------------------------
export my_ssh=${chimere_root}/ssh-aerosol/src/

